### ISSUE TITLE
How to precompile assets in heroku?

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [efficiently/laravel_larasset_app#1]
I am trying to figure out how to precompile assets in heroku. Please help.

**Comment by tortuetorche** [comment]
Hi @prathamesh-sonpatki, 

You should precompile your assets locally then push the precompiled assets to your Heroku repository.

I think it's the simple and safest way.

And it's what I did for this [Larasset demo](http://larasset.herokuapp.com).

**Comment by prathamesh-sonpatki** [comment]
Thanks for the explanation :smile:
